version: "3.8"

services:
  redis-stack-server:
    container_name: redis-stack-server
    image: redis-stack-server
    ports: 
      - 6379:6379
    networks:
      - article-network
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    networks:
      - article-network
networks:
  article-network:
    name: article-network
